version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "dme86"

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - "dme86"
