---
apiVersion: v1
kind: Namespace
metadata:
    name: testing
    labels:
      environment: testing
      customer: foo 
---
apiVersion: v1
kind: Namespace
metadata:
    name: development
    labels:
      environment: development
      customer: foo
---
apiVersion: v1
kind: Namespace
metadata:
    name: production
    labels:
      environment: production
      customer: foo
