apiVersion: v1
kind: Pod
metadata:
  name: nginx-hello-2
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginxdemos/hello:0.3
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
